baseURL = "http://manifold.finance/hub"
languageCode = "en-us"
title = "Manifold Finance Hub"
# Book configuration
disablePathToLower = false
enableGitInfo = true
# (Optional) Theme is intended for documentation use, therefore it doesn't render taxonomy.
# You can remove related files with config below
disableKinds = ['taxonomy', 'taxonomyTerm']

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[menu]
# [[menu.before]]
[[menu.main]]
  identifier = 'Telegram'
  name = 'Telegram'
  pre = "<i class='fa fa-heart'></i>"
  url = 'https://t.me/manifoldfinance'
  weight = -110
[[menu.main]]
  name = 'GitHub'
  post = "<span class='alert'>New!</span>"
  pre = "<i class='fa fa-road'></i>"
  url = 'https://github.com/manifoldfinance'
  weight = -100
[[menu.after]]
  name = "View on Github"
  url = "https://github.com/manifoldfinance/hub"
  weight = 10


# see https://themes.gohugo.io/hugo-book/ for options
[params]
  BookTheme = 'auto'
  BookToC = true
  # BookLogo = 'logo.png'
  BookSection = 'docs'
  BookRepo = 'https://github.com/manifoldfinance/hub.github.io'
  BookCommitPath = 'commit'
  BookEditPath = 'edit/main/content'

  # (Optional, default January 2, 2006) Configure the date format used on the pages
  # - In git information
  # - In blog posts
  BookDateFormat = '02.01.2006'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'


[build]
  publish = "www/src/public"
  command = "hugo -s www/src --gc"

[build.environment]
  HUGO_THEME = "repo"
  HUGO_THEMESDIR = "/opt/build"
  HUGO_VERSION = "0.80.0"

[context.production.environment]
  HUGO_BASEURL = "https://manifold-hub.netlify.app/"

[context.deploy-preview]
  command = "hugo -s www/src --gc --buildFuture -b $DEPLOY_PRIME_URL"